### ISSUE TITLE
Unreliable image cache due to hash collisions

### ISSUE THREAD

**Issue by deresov** [x2on/FSImageViewer#28]
In "FSImageLoader.m" on line 79 [NSString hash] method is used to create a cache key:

    NSString *cacheKey = [NSString stringWithFormat:@"FSImageLoader-%lu", (unsigned long)[[aURL description] hash]];

This causes problems with long image URLs, because "hash" method of NSString only uses 96 characters to generate the hash (first 32, last 32 and middle 32). Basically if your URLs are over 96 chars in length, there is a good chance of getting the same cacheKey for two different URLs. I run into this problem because I had a bunch of long, similar URLs where the only difference was the product id (starting at char 39).

[This article](http://www.abakia.de/blog/2012/12/05/nsstring-hash-is-bad/) describes the problem in detail.

Would it be possible to use a more robust hash function? Here is an implementation using MD5 hash:

    - (NSString *)getMD5ValueForURL:(NSURL*)aURL {
        const char *urlString = [[aURL absoluteString] UTF8String];
        unsigned char hashBytes[CC_MD5_DIGEST_LENGTH];
        CC_MD5(urlString, strlen(urlString), hashBytes);
    
        NSMutableString *hashString = [NSMutableString stringWithCapacity:CC_MD5_DIGEST_LENGTH * 2];
        for ( NSInteger i = 0; i < CC_MD5_DIGEST_LENGTH; i++ ) {
            [hashString appendFormat:@"%02x", hashBytes[i]];
        }
    
        return hashString;
    }

**Comment by x2on** [comment]
Sorry for the delay - is now in version 3.0
