### ISSUE TITLE
Rotation Problem

### ISSUE THREAD

**Issue by andre1720** [x2on/FSImageViewer#35]
Hi,
I've some problem when i rotate my device.
I can repeat the issue when i push in portrait and then i rotate in landscape mode.
You can see it in the attached image!
I've 3.2 version and iOs8
![img_6009](https://cloud.githubusercontent.com/assets/3781468/7836002/6c4c6b64-047d-11e5-90fc-34f679344ec1.PNG)

Thanks

**Comment by andre1720** [comment]
The issue it's only on iphone 6 and 6 plus!

**Comment by x2on** [comment]
Hi @andre1720 ,

i could not reproduce the issue. Could you please provide some details or a sample project?

**Comment by andre1720** [comment]
Hi @x2on,

this is my code for present the navigation controller:


NSMutableArray * photoArray = [[NSMutableArray alloc] init];
    for (NSDictionary *key in arrayImages) {
        FSBasicImage *photo = [[FSBasicImage alloc] initWithImageURL:[NSURL URLWithString:[key objectForKey:@"picture_url"]] name:currentCar.nameCar];
        [photoArray addObject:photo];
    }
    FSBasicImageSource *photoSource = [[FSBasicImageSource alloc] initWithImages:[[photoArray reverseObjectEnumerator] allObjects]];
    
    FSImageViewerViewController *imageViewController = [[FSImageViewerViewController alloc] initWithImageSource:photoSource];
    imageViewController.delegate = self;
    NSNumber *index = [[notification userInfo] objectForKey:@"index" ];
    [imageViewController moveToImageAtIndex:index.intValue animated:YES];
    
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:imageViewController];
    [self.navigationController presentViewController:navigationController animated:YES completion:nil];

**Comment by andre1720** [comment]
Sorry, all iOs 8 Device have this issue!

**Comment by andre1720** [comment]
I'm using this slide menu with his navigation controller:
https://github.com/aryaxt/iOS-Slide-Menu

**Comment by x2on** [comment]
I still could not reproduce the issue. If you still have the problem please feel free to reopen.
