### ISSUE TITLE
The demo does not build with Xcode 6.4

### ISSUE THREAD

**Issue by franklindner** [x2on/FSImageViewer#39]
AS the title says I imported the latest version 3.4 via cocoa pods in my project and it gave me build errors, so I downloaded the DEMO project and it does not build either. Maybe I am missing something super obvious but usually it should just be 'pod install' and thats it.
![screen shot 2015-10-11 at 19 07 08](https://cloud.githubusercontent.com/assets/2862091/10417877/4b637ed0-704b-11e5-99cc-68fa427e29c3.png)

**Comment by x2on** [comment]
For the latest version you need Xcode 7.

**Comment by franklindner** [comment]
Ok I see, what is the latest version compatible with Xcode 6.4?

**Comment by x2on** [comment]
3.2 should be fine.

**Comment by franklindner** [comment]
It worked thanks ;)
